require('./components/preloader')
require('./components/animations')
require('./components/benefits')
require('./components/product-slider')
require('./components/menu')
require('./components/call-modal')
require('./components/additional')
require('./components/workshop')
