<?
$PERM["personal"]["6"]="W";
$PERM["index.php"]["6"]="W";
$PERM["info"]["6"]="W";
$PERM["contacts"]["6"]="W";
$PERM[".top.menu.php"]["6"]="W";
$PERM[".bottom.menu.php"]["6"]="W";
$PERM["include"]["6"]="W";
$PERM["/"]["*"]="R";
?>