require('./components/header')
require('./components/faqDrop')
require('./components/product-specs')
require('./components/product-slider')
require('./components/product-tabs')
require('./components/video')
require('./components/request-form')
